# Generated by Django 4.2.7 on 2025-04-13 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('coin_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='rub', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='crypto_icons/')),
            ],
            options={
                'verbose_name': 'Криптовалюта',
                'verbose_name_plural': 'Криптовалюты',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='web.telegramuser')),
                ('coin_id', models.CharField(default='fpi-bank', max_length=50)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(default=0.1)),
                ('depozit', models.FloatField(default=0)),
                ('last_notified_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
        migrations.CreateModel(
            name='AdminBroadcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='web.telegramuser')),
            ],
            options={
                'verbose_name': 'Рассылка администратора',
                'verbose_name_plural': 'Рассылки администратора',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='web.cryptocurrency')),
            ],
            options={
                'verbose_name': 'Цена криптовалюты',
                'verbose_name_plural': 'Цены криптовалют',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cryptocurrency', 'timestamp'], name='web_priceda_cryptoc_4f63f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='web.adminbroadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.telegramuser')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
                'unique_together': {('broadcast', 'user')},
            },
        ),
    ]
